// This file is auto-generated by @hey-api/openapi-ts

export const FoodLeftSchemaSchema = {
    properties: {
        food: {
            title: 'Food',
            type: 'string'
        },
        foodleft: {
            title: 'Foodleft',
            type: 'integer'
        }
    },
    required: ['food', 'foodleft'],
    title: 'FoodLeftSchema',
    type: 'object'
} as const;

export const FoodSchemaSchema = {
    properties: {
        food: {
            items: {
                type: 'string'
            },
            title: 'Food',
            type: 'array'
        }
    },
    required: ['food'],
    title: 'FoodSchema',
    type: 'object'
} as const;